// flow-typed signature: 3860cbabe61ce957f33695a94e4bfff5
// flow-typed version: <<STUB>>/normalize.scss_v^0.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.scss' {
  declare module.exports: any;
}
