// flow-typed signature: 8703a74d1c0661e7a8ea7643b78e3173
// flow-typed version: <<STUB>>/react-tools_v^0.13.3/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tools/main' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/__tests__/ReactFragment-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/__tests__/update-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/link/__tests__/LinkedStateMixin-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/link/__tests__/ReactLinkPropTypes-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/link/LinkedStateMixin' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/link/ReactLink' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/ReactComponentWithPureRenderMixin' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/ReactFragment' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/ReactRAFBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/__tests__/ReactCSSTransitionGroup-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/__tests__/ReactTransitionChildMapping-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/__tests__/ReactTransitionGroup-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/ReactCSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/ReactCSSTransitionGroupChild' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/ReactTransitionChildMapping' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/transitions/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'react-tools/src/addons/update' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/__tests__/findDOMNode-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/__tests__/ReactBrowserEventEmitter-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/__tests__/ReactDOM-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/__tests__/ReactWebWorker-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ClientReactRootIndex' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/__tests__/AnalyticsEventPlugin-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/__tests__/EnterLeaveEventPlugin-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/__tests__/FallbackCompositionState-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/__tests__/ResponderEventPlugin-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/AnalyticsEventPluginFactory' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/BeforeInputEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/ChangeEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/DefaultEventPluginOrder' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/EnterLeaveEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/FallbackCompositionState' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/MobileSafariClickEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/ResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/SelectEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/SimpleEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/eventPlugins/TapEventPlugin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/findDOMNode' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ReactBrowserEventEmitter' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ReactDOM' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ReactPutListenerQueue' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ReactReconcileTransaction' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ReactWithAddons' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/server/__tests__/ReactServerRendering-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/server/ReactMarkupChecksum' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/server/ReactServerRendering' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/server/ReactServerRenderingTransaction' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/server/ServerReactRootIndex' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/__tests__/SyntheticEvent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/__tests__/SyntheticWheelEvent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticClipboardEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticCompositionEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticDragEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticFocusEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticInputEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticKeyboardEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticMouseEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticTouchEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticUIEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/syntheticEvents/SyntheticWheelEvent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactDOMComponent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactDOMIDOperations-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactDOMTextComponent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactEventListener-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactMount-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactMountDestruction-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/__tests__/ReactRenderDocument-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/__tests__/CSSProperty-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/__tests__/CSSPropertyOperations-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/__tests__/Danger-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/__tests__/DOMPropertyOperations-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/__tests__/getNodeForCharacterOffset-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/__tests__/LocalEventTrapMixin-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMButton-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMIframe-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMInput-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMSelect-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMTextarea-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/AutoFocusMixin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/createFullPageComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/LinkedValueUtils' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/LocalEventTrapMixin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMButton' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMForm' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMIframe' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMImg' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMInput' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMOption' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMSelect' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/components/ReactDOMTextarea' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/CSSProperty' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/CSSPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/Danger' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/dangerousStyleValue' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/DOMChildrenOperations' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/DOMProperty' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/DOMPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/getEventCharCode' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/getEventKey' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/getEventModifierState' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/getEventTarget' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/getNodeForCharacterOffset' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/getTextContentAccessor' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/HTMLDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/isEventSupported' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/setInnerHTML' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/setTextContent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/SVGDOMPropertyConfig' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/dom/ViewportMetrics' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/getReactRootElementInContainer' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/React' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactBrowserComponentMixin' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactComponentBrowserEnvironment' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactDefaultInjection' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactDOMComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactDOMIDOperations' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactDOMSelection' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactDOMTextComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactEventListener' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactInjection' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactInputSelection' {
  declare module.exports: any;
}

declare module 'react-tools/src/browser/ui/ReactMount' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/__tests__/ReactContextValidator-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/class/__tests__/ReactBind-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/class/__tests__/ReactClass-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/class/__tests__/ReactClassMixin-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/class/ReactClass' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/class/ReactDoNotBindDeprecated' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/element/__tests__/ReactElement-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/element/__tests__/ReactElementClone-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/element/__tests__/ReactElementValidator-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/element/ReactElement' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/element/ReactElementValidator' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/types/__tests__/ReactPropTypes-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/types/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/types/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react-tools/src/classic/types/ReactPropTypes' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactComponent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactComponentLifeCycle-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactCompositeComponent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactCompositeComponentDOMMinimalism-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactCompositeComponentError-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactCompositeComponentNestedState-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactCompositeComponentState-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactEmptyComponent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactIdentity-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactInstanceHandles-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactMockedComponent-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactMultiChild-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactMultiChildReconcile-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactMultiChildText-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactStateSetters-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/ReactUpdates-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/refs-destruction-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/__tests__/refs-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/instantiateReactComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactChildReconciler' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactComponentEnvironment' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactContext' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactCurrentOwner' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactDefaultBatchingStrategy' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactEmptyComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactEventEmitterMixin' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactInstanceHandles' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactInstanceMap' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactLifeCycle' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactMultiChild' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactMultiChildUpdateTypes' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactNativeComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactOwner' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactPropTransferer' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactReconciler' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactRef' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactRootIndex' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactStateSetters' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactUpdateQueue' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/ReactUpdates' {
  declare module.exports: any;
}

declare module 'react-tools/src/core/shouldUpdateReactComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/__tests__/EventPluginHub-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/__tests__/EventPluginRegistry-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/EventConstants' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/EventPluginHub' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/EventPluginRegistry' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'react-tools/src/event/EventPropagators' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/class/__tests__/ReactClassEquivalence-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/class/__tests__/ReactES6Class-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/class/ReactComponent' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/element/__tests__/ReactJSXElement-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/element/__tests__/ReactJSXElementValidator-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/types/__tests__/ReactFlowPropTypes-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/modern/types/__tests__/ReactTypeScriptPropTypes-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/stubs/Object.assign' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/__tests__/MetaMatchers-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/__tests__/reactComponentExpect-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/__tests__/ReactTestUtils-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/all' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/createHierarchyRenderer' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/getTestDocument' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/MetaMatchers' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/mock-modules' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/mock-timers' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/mocks' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/phantomjs-shims' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/reactComponentExpect' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/ReactDefaultPerf' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/ReactDefaultPerfAnalysis' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/ReactPerf' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/ReactTestUtils' {
  declare module.exports: any;
}

declare module 'react-tools/src/test/worker' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/accumulateInto-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/cloneWithProps-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/escapeTextContentForBrowser-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/joinClasses-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/memoizeStringOnly-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/onlyChild-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/OrderedMap-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/PooledClass-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/quoteAttributeValueForBrowser-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/ReactChildren-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/sliceChildren-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/Transaction-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/__tests__/traverseAllChildren-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/accumulate' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/accumulateInto' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/adler32' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/CallbackQueue' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/cloneWithProps' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/deprecated' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/escapeTextContentForBrowser' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/flattenChildren' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/forEachAccumulated' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/isTextInputElement' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/joinClasses' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/memoizeStringOnly' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/onlyChild' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/OrderedMap' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/PooledClass' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/quoteAttributeValueForBrowser' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/ReactChildren' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/sliceChildren' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/Transaction' {
  declare module.exports: any;
}

declare module 'react-tools/src/utils/traverseAllChildren' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/camelize' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/camelizeStyleName' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/createArrayFromMixed' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/createNodesFromMarkup' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/CSSCore' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/dom/containsNode' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/dom/focusNode' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/dom/getActiveElement' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/dom/getUnboundedScrollPosition' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/dom/isNode' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/dom/isTextNode' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/emptyFunction' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/emptyObject' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/getMarkupWrap' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/hyphenate' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/hyphenateStyleName' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/invariant' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/mapObject' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/monitorCodeUse' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/nativeRequestAnimationFrame' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/toArray' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/TouchEventUtils' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/core/warning' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/key-mirror/__tests__/keyMirror-test' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/key-mirror/keyMirror' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/key-mirror/keyOf' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/performance/performance' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/performance/performanceNow' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/stubs/cx' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/stubs/EventListener' {
  declare module.exports: any;
}

declare module 'react-tools/src/vendor/stubs/ReactErrorUtils' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/syntax' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/transforms/__tests__/jsx-test' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/transforms/__tests__/react-displayName-test' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/transforms/__tests__/react-test' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/transforms/jsx' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/transforms/react' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/transforms/reactDisplayName' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/fbtransform/visitors' {
  declare module.exports: any;
}

declare module 'react-tools/vendor/inline-source-map' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tools/main.js' {
  declare module.exports: $Exports<'react-tools/main'>;
}
declare module 'react-tools/src/addons/__tests__/ReactFragment-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/__tests__/ReactFragment-test'>;
}
declare module 'react-tools/src/addons/__tests__/update-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/__tests__/update-test'>;
}
declare module 'react-tools/src/addons/link/__tests__/LinkedStateMixin-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/link/__tests__/LinkedStateMixin-test'>;
}
declare module 'react-tools/src/addons/link/__tests__/ReactLinkPropTypes-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/link/__tests__/ReactLinkPropTypes-test'>;
}
declare module 'react-tools/src/addons/link/LinkedStateMixin.js' {
  declare module.exports: $Exports<'react-tools/src/addons/link/LinkedStateMixin'>;
}
declare module 'react-tools/src/addons/link/ReactLink.js' {
  declare module.exports: $Exports<'react-tools/src/addons/link/ReactLink'>;
}
declare module 'react-tools/src/addons/ReactComponentWithPureRenderMixin.js' {
  declare module.exports: $Exports<'react-tools/src/addons/ReactComponentWithPureRenderMixin'>;
}
declare module 'react-tools/src/addons/ReactFragment.js' {
  declare module.exports: $Exports<'react-tools/src/addons/ReactFragment'>;
}
declare module 'react-tools/src/addons/ReactRAFBatchingStrategy.js' {
  declare module.exports: $Exports<'react-tools/src/addons/ReactRAFBatchingStrategy'>;
}
declare module 'react-tools/src/addons/transitions/__tests__/ReactCSSTransitionGroup-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/__tests__/ReactCSSTransitionGroup-test'>;
}
declare module 'react-tools/src/addons/transitions/__tests__/ReactTransitionChildMapping-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/__tests__/ReactTransitionChildMapping-test'>;
}
declare module 'react-tools/src/addons/transitions/__tests__/ReactTransitionGroup-test.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/__tests__/ReactTransitionGroup-test'>;
}
declare module 'react-tools/src/addons/transitions/ReactCSSTransitionGroup.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/ReactCSSTransitionGroup'>;
}
declare module 'react-tools/src/addons/transitions/ReactCSSTransitionGroupChild.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/ReactCSSTransitionGroupChild'>;
}
declare module 'react-tools/src/addons/transitions/ReactTransitionChildMapping.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/ReactTransitionChildMapping'>;
}
declare module 'react-tools/src/addons/transitions/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/ReactTransitionEvents'>;
}
declare module 'react-tools/src/addons/transitions/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'react-tools/src/addons/transitions/ReactTransitionGroup'>;
}
declare module 'react-tools/src/addons/update.js' {
  declare module.exports: $Exports<'react-tools/src/addons/update'>;
}
declare module 'react-tools/src/browser/__tests__/findDOMNode-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/__tests__/findDOMNode-test'>;
}
declare module 'react-tools/src/browser/__tests__/ReactBrowserEventEmitter-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/__tests__/ReactBrowserEventEmitter-test'>;
}
declare module 'react-tools/src/browser/__tests__/ReactDOM-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/__tests__/ReactDOM-test'>;
}
declare module 'react-tools/src/browser/__tests__/ReactWebWorker-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/__tests__/ReactWebWorker-test'>;
}
declare module 'react-tools/src/browser/ClientReactRootIndex.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ClientReactRootIndex'>;
}
declare module 'react-tools/src/browser/eventPlugins/__tests__/AnalyticsEventPlugin-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/__tests__/AnalyticsEventPlugin-test'>;
}
declare module 'react-tools/src/browser/eventPlugins/__tests__/EnterLeaveEventPlugin-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/__tests__/EnterLeaveEventPlugin-test'>;
}
declare module 'react-tools/src/browser/eventPlugins/__tests__/FallbackCompositionState-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/__tests__/FallbackCompositionState-test'>;
}
declare module 'react-tools/src/browser/eventPlugins/__tests__/ResponderEventPlugin-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/__tests__/ResponderEventPlugin-test'>;
}
declare module 'react-tools/src/browser/eventPlugins/AnalyticsEventPluginFactory.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/AnalyticsEventPluginFactory'>;
}
declare module 'react-tools/src/browser/eventPlugins/BeforeInputEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/BeforeInputEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/ChangeEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/ChangeEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/DefaultEventPluginOrder.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/DefaultEventPluginOrder'>;
}
declare module 'react-tools/src/browser/eventPlugins/EnterLeaveEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/EnterLeaveEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/FallbackCompositionState.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/FallbackCompositionState'>;
}
declare module 'react-tools/src/browser/eventPlugins/MobileSafariClickEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/MobileSafariClickEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/ResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/ResponderEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/SelectEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/SelectEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/SimpleEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/SimpleEventPlugin'>;
}
declare module 'react-tools/src/browser/eventPlugins/TapEventPlugin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/eventPlugins/TapEventPlugin'>;
}
declare module 'react-tools/src/browser/findDOMNode.js' {
  declare module.exports: $Exports<'react-tools/src/browser/findDOMNode'>;
}
declare module 'react-tools/src/browser/ReactBrowserEventEmitter.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ReactBrowserEventEmitter'>;
}
declare module 'react-tools/src/browser/ReactDOM.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ReactDOM'>;
}
declare module 'react-tools/src/browser/ReactPutListenerQueue.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ReactPutListenerQueue'>;
}
declare module 'react-tools/src/browser/ReactReconcileTransaction.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ReactReconcileTransaction'>;
}
declare module 'react-tools/src/browser/ReactWithAddons.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ReactWithAddons'>;
}
declare module 'react-tools/src/browser/server/__tests__/ReactServerRendering-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/server/__tests__/ReactServerRendering-test'>;
}
declare module 'react-tools/src/browser/server/ReactMarkupChecksum.js' {
  declare module.exports: $Exports<'react-tools/src/browser/server/ReactMarkupChecksum'>;
}
declare module 'react-tools/src/browser/server/ReactServerRendering.js' {
  declare module.exports: $Exports<'react-tools/src/browser/server/ReactServerRendering'>;
}
declare module 'react-tools/src/browser/server/ReactServerRenderingTransaction.js' {
  declare module.exports: $Exports<'react-tools/src/browser/server/ReactServerRenderingTransaction'>;
}
declare module 'react-tools/src/browser/server/ServerReactRootIndex.js' {
  declare module.exports: $Exports<'react-tools/src/browser/server/ServerReactRootIndex'>;
}
declare module 'react-tools/src/browser/syntheticEvents/__tests__/SyntheticEvent-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/__tests__/SyntheticEvent-test'>;
}
declare module 'react-tools/src/browser/syntheticEvents/__tests__/SyntheticWheelEvent-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/__tests__/SyntheticWheelEvent-test'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticClipboardEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticClipboardEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticCompositionEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticCompositionEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticDragEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticDragEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticFocusEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticFocusEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticInputEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticInputEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticKeyboardEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticKeyboardEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticMouseEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticMouseEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticTouchEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticTouchEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticUIEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticUIEvent'>;
}
declare module 'react-tools/src/browser/syntheticEvents/SyntheticWheelEvent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/syntheticEvents/SyntheticWheelEvent'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactDOMComponent-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactDOMComponent-test'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactDOMIDOperations-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactDOMIDOperations-test'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactDOMTextComponent-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactDOMTextComponent-test'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactEventListener-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactEventListener-test'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactMount-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactMount-test'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactMountDestruction-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactMountDestruction-test'>;
}
declare module 'react-tools/src/browser/ui/__tests__/ReactRenderDocument-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/__tests__/ReactRenderDocument-test'>;
}
declare module 'react-tools/src/browser/ui/dom/__tests__/CSSProperty-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/__tests__/CSSProperty-test'>;
}
declare module 'react-tools/src/browser/ui/dom/__tests__/CSSPropertyOperations-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/__tests__/CSSPropertyOperations-test'>;
}
declare module 'react-tools/src/browser/ui/dom/__tests__/Danger-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/__tests__/Danger-test'>;
}
declare module 'react-tools/src/browser/ui/dom/__tests__/DOMPropertyOperations-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/__tests__/DOMPropertyOperations-test'>;
}
declare module 'react-tools/src/browser/ui/dom/__tests__/getNodeForCharacterOffset-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/__tests__/getNodeForCharacterOffset-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/__tests__/LocalEventTrapMixin-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/__tests__/LocalEventTrapMixin-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMButton-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMButton-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMIframe-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMIframe-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMInput-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMInput-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMSelect-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMSelect-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMTextarea-test.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/__tests__/ReactDOMTextarea-test'>;
}
declare module 'react-tools/src/browser/ui/dom/components/AutoFocusMixin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/AutoFocusMixin'>;
}
declare module 'react-tools/src/browser/ui/dom/components/createFullPageComponent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/createFullPageComponent'>;
}
declare module 'react-tools/src/browser/ui/dom/components/LinkedValueUtils.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/LinkedValueUtils'>;
}
declare module 'react-tools/src/browser/ui/dom/components/LocalEventTrapMixin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/LocalEventTrapMixin'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMButton.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMButton'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMForm.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMForm'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMIframe.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMIframe'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMImg.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMImg'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMInput.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMInput'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMOption.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMOption'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMSelect.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMSelect'>;
}
declare module 'react-tools/src/browser/ui/dom/components/ReactDOMTextarea.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/components/ReactDOMTextarea'>;
}
declare module 'react-tools/src/browser/ui/dom/CSSProperty.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/CSSProperty'>;
}
declare module 'react-tools/src/browser/ui/dom/CSSPropertyOperations.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/CSSPropertyOperations'>;
}
declare module 'react-tools/src/browser/ui/dom/Danger.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/Danger'>;
}
declare module 'react-tools/src/browser/ui/dom/dangerousStyleValue.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/dangerousStyleValue'>;
}
declare module 'react-tools/src/browser/ui/dom/DOMChildrenOperations.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/DOMChildrenOperations'>;
}
declare module 'react-tools/src/browser/ui/dom/DOMProperty.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/DOMProperty'>;
}
declare module 'react-tools/src/browser/ui/dom/DOMPropertyOperations.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/DOMPropertyOperations'>;
}
declare module 'react-tools/src/browser/ui/dom/getEventCharCode.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/getEventCharCode'>;
}
declare module 'react-tools/src/browser/ui/dom/getEventKey.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/getEventKey'>;
}
declare module 'react-tools/src/browser/ui/dom/getEventModifierState.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/getEventModifierState'>;
}
declare module 'react-tools/src/browser/ui/dom/getEventTarget.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/getEventTarget'>;
}
declare module 'react-tools/src/browser/ui/dom/getNodeForCharacterOffset.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/getNodeForCharacterOffset'>;
}
declare module 'react-tools/src/browser/ui/dom/getTextContentAccessor.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/getTextContentAccessor'>;
}
declare module 'react-tools/src/browser/ui/dom/HTMLDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/HTMLDOMPropertyConfig'>;
}
declare module 'react-tools/src/browser/ui/dom/isEventSupported.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/isEventSupported'>;
}
declare module 'react-tools/src/browser/ui/dom/setInnerHTML.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/setInnerHTML'>;
}
declare module 'react-tools/src/browser/ui/dom/setTextContent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/setTextContent'>;
}
declare module 'react-tools/src/browser/ui/dom/SVGDOMPropertyConfig.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/SVGDOMPropertyConfig'>;
}
declare module 'react-tools/src/browser/ui/dom/ViewportMetrics.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/dom/ViewportMetrics'>;
}
declare module 'react-tools/src/browser/ui/getReactRootElementInContainer.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/getReactRootElementInContainer'>;
}
declare module 'react-tools/src/browser/ui/React.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/React'>;
}
declare module 'react-tools/src/browser/ui/ReactBrowserComponentMixin.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactBrowserComponentMixin'>;
}
declare module 'react-tools/src/browser/ui/ReactComponentBrowserEnvironment.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactComponentBrowserEnvironment'>;
}
declare module 'react-tools/src/browser/ui/ReactDefaultInjection.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactDefaultInjection'>;
}
declare module 'react-tools/src/browser/ui/ReactDOMComponent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactDOMComponent'>;
}
declare module 'react-tools/src/browser/ui/ReactDOMIDOperations.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactDOMIDOperations'>;
}
declare module 'react-tools/src/browser/ui/ReactDOMSelection.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactDOMSelection'>;
}
declare module 'react-tools/src/browser/ui/ReactDOMTextComponent.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactDOMTextComponent'>;
}
declare module 'react-tools/src/browser/ui/ReactEventListener.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactEventListener'>;
}
declare module 'react-tools/src/browser/ui/ReactInjection.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactInjection'>;
}
declare module 'react-tools/src/browser/ui/ReactInputSelection.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactInputSelection'>;
}
declare module 'react-tools/src/browser/ui/ReactMount.js' {
  declare module.exports: $Exports<'react-tools/src/browser/ui/ReactMount'>;
}
declare module 'react-tools/src/classic/__tests__/ReactContextValidator-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/__tests__/ReactContextValidator-test'>;
}
declare module 'react-tools/src/classic/class/__tests__/ReactBind-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/class/__tests__/ReactBind-test'>;
}
declare module 'react-tools/src/classic/class/__tests__/ReactClass-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/class/__tests__/ReactClass-test'>;
}
declare module 'react-tools/src/classic/class/__tests__/ReactClassMixin-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/class/__tests__/ReactClassMixin-test'>;
}
declare module 'react-tools/src/classic/class/ReactClass.js' {
  declare module.exports: $Exports<'react-tools/src/classic/class/ReactClass'>;
}
declare module 'react-tools/src/classic/class/ReactDoNotBindDeprecated.js' {
  declare module.exports: $Exports<'react-tools/src/classic/class/ReactDoNotBindDeprecated'>;
}
declare module 'react-tools/src/classic/element/__tests__/ReactElement-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/element/__tests__/ReactElement-test'>;
}
declare module 'react-tools/src/classic/element/__tests__/ReactElementClone-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/element/__tests__/ReactElementClone-test'>;
}
declare module 'react-tools/src/classic/element/__tests__/ReactElementValidator-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/element/__tests__/ReactElementValidator-test'>;
}
declare module 'react-tools/src/classic/element/ReactElement.js' {
  declare module.exports: $Exports<'react-tools/src/classic/element/ReactElement'>;
}
declare module 'react-tools/src/classic/element/ReactElementValidator.js' {
  declare module.exports: $Exports<'react-tools/src/classic/element/ReactElementValidator'>;
}
declare module 'react-tools/src/classic/types/__tests__/ReactPropTypes-test.js' {
  declare module.exports: $Exports<'react-tools/src/classic/types/__tests__/ReactPropTypes-test'>;
}
declare module 'react-tools/src/classic/types/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react-tools/src/classic/types/ReactPropTypeLocationNames'>;
}
declare module 'react-tools/src/classic/types/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react-tools/src/classic/types/ReactPropTypeLocations'>;
}
declare module 'react-tools/src/classic/types/ReactPropTypes.js' {
  declare module.exports: $Exports<'react-tools/src/classic/types/ReactPropTypes'>;
}
declare module 'react-tools/src/core/__tests__/ReactComponent-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactComponent-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactComponentLifeCycle-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactComponentLifeCycle-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactCompositeComponent-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactCompositeComponent-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactCompositeComponentDOMMinimalism-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactCompositeComponentDOMMinimalism-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactCompositeComponentError-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactCompositeComponentError-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactCompositeComponentNestedState-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactCompositeComponentNestedState-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactCompositeComponentState-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactCompositeComponentState-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactEmptyComponent-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactEmptyComponent-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactIdentity-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactIdentity-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactInstanceHandles-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactInstanceHandles-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactMockedComponent-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactMockedComponent-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactMultiChild-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactMultiChild-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactMultiChildReconcile-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactMultiChildReconcile-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactMultiChildText-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactMultiChildText-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactStateSetters-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactStateSetters-test'>;
}
declare module 'react-tools/src/core/__tests__/ReactUpdates-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/ReactUpdates-test'>;
}
declare module 'react-tools/src/core/__tests__/refs-destruction-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/refs-destruction-test'>;
}
declare module 'react-tools/src/core/__tests__/refs-test.js' {
  declare module.exports: $Exports<'react-tools/src/core/__tests__/refs-test'>;
}
declare module 'react-tools/src/core/instantiateReactComponent.js' {
  declare module.exports: $Exports<'react-tools/src/core/instantiateReactComponent'>;
}
declare module 'react-tools/src/core/ReactChildReconciler.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactChildReconciler'>;
}
declare module 'react-tools/src/core/ReactComponentEnvironment.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactComponentEnvironment'>;
}
declare module 'react-tools/src/core/ReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactCompositeComponent'>;
}
declare module 'react-tools/src/core/ReactContext.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactContext'>;
}
declare module 'react-tools/src/core/ReactCurrentOwner.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactCurrentOwner'>;
}
declare module 'react-tools/src/core/ReactDefaultBatchingStrategy.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactDefaultBatchingStrategy'>;
}
declare module 'react-tools/src/core/ReactEmptyComponent.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactEmptyComponent'>;
}
declare module 'react-tools/src/core/ReactEventEmitterMixin.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactEventEmitterMixin'>;
}
declare module 'react-tools/src/core/ReactInstanceHandles.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactInstanceHandles'>;
}
declare module 'react-tools/src/core/ReactInstanceMap.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactInstanceMap'>;
}
declare module 'react-tools/src/core/ReactLifeCycle.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactLifeCycle'>;
}
declare module 'react-tools/src/core/ReactMultiChild.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactMultiChild'>;
}
declare module 'react-tools/src/core/ReactMultiChildUpdateTypes.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactMultiChildUpdateTypes'>;
}
declare module 'react-tools/src/core/ReactNativeComponent.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactNativeComponent'>;
}
declare module 'react-tools/src/core/ReactOwner.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactOwner'>;
}
declare module 'react-tools/src/core/ReactPropTransferer.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactPropTransferer'>;
}
declare module 'react-tools/src/core/ReactReconciler.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactReconciler'>;
}
declare module 'react-tools/src/core/ReactRef.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactRef'>;
}
declare module 'react-tools/src/core/ReactRootIndex.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactRootIndex'>;
}
declare module 'react-tools/src/core/ReactStateSetters.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactStateSetters'>;
}
declare module 'react-tools/src/core/ReactUpdateQueue.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactUpdateQueue'>;
}
declare module 'react-tools/src/core/ReactUpdates.js' {
  declare module.exports: $Exports<'react-tools/src/core/ReactUpdates'>;
}
declare module 'react-tools/src/core/shouldUpdateReactComponent.js' {
  declare module.exports: $Exports<'react-tools/src/core/shouldUpdateReactComponent'>;
}
declare module 'react-tools/src/event/__tests__/EventPluginHub-test.js' {
  declare module.exports: $Exports<'react-tools/src/event/__tests__/EventPluginHub-test'>;
}
declare module 'react-tools/src/event/__tests__/EventPluginRegistry-test.js' {
  declare module.exports: $Exports<'react-tools/src/event/__tests__/EventPluginRegistry-test'>;
}
declare module 'react-tools/src/event/EventConstants.js' {
  declare module.exports: $Exports<'react-tools/src/event/EventConstants'>;
}
declare module 'react-tools/src/event/EventPluginHub.js' {
  declare module.exports: $Exports<'react-tools/src/event/EventPluginHub'>;
}
declare module 'react-tools/src/event/EventPluginRegistry.js' {
  declare module.exports: $Exports<'react-tools/src/event/EventPluginRegistry'>;
}
declare module 'react-tools/src/event/EventPluginUtils.js' {
  declare module.exports: $Exports<'react-tools/src/event/EventPluginUtils'>;
}
declare module 'react-tools/src/event/EventPropagators.js' {
  declare module.exports: $Exports<'react-tools/src/event/EventPropagators'>;
}
declare module 'react-tools/src/modern/class/__tests__/ReactClassEquivalence-test.js' {
  declare module.exports: $Exports<'react-tools/src/modern/class/__tests__/ReactClassEquivalence-test'>;
}
declare module 'react-tools/src/modern/class/__tests__/ReactES6Class-test.js' {
  declare module.exports: $Exports<'react-tools/src/modern/class/__tests__/ReactES6Class-test'>;
}
declare module 'react-tools/src/modern/class/ReactComponent.js' {
  declare module.exports: $Exports<'react-tools/src/modern/class/ReactComponent'>;
}
declare module 'react-tools/src/modern/element/__tests__/ReactJSXElement-test.js' {
  declare module.exports: $Exports<'react-tools/src/modern/element/__tests__/ReactJSXElement-test'>;
}
declare module 'react-tools/src/modern/element/__tests__/ReactJSXElementValidator-test.js' {
  declare module.exports: $Exports<'react-tools/src/modern/element/__tests__/ReactJSXElementValidator-test'>;
}
declare module 'react-tools/src/modern/types/__tests__/ReactFlowPropTypes-test.js' {
  declare module.exports: $Exports<'react-tools/src/modern/types/__tests__/ReactFlowPropTypes-test'>;
}
declare module 'react-tools/src/modern/types/__tests__/ReactTypeScriptPropTypes-test.js' {
  declare module.exports: $Exports<'react-tools/src/modern/types/__tests__/ReactTypeScriptPropTypes-test'>;
}
declare module 'react-tools/src/stubs/Object.assign.js' {
  declare module.exports: $Exports<'react-tools/src/stubs/Object.assign'>;
}
declare module 'react-tools/src/test/__tests__/MetaMatchers-test.js' {
  declare module.exports: $Exports<'react-tools/src/test/__tests__/MetaMatchers-test'>;
}
declare module 'react-tools/src/test/__tests__/reactComponentExpect-test.js' {
  declare module.exports: $Exports<'react-tools/src/test/__tests__/reactComponentExpect-test'>;
}
declare module 'react-tools/src/test/__tests__/ReactTestUtils-test.js' {
  declare module.exports: $Exports<'react-tools/src/test/__tests__/ReactTestUtils-test'>;
}
declare module 'react-tools/src/test/all.js' {
  declare module.exports: $Exports<'react-tools/src/test/all'>;
}
declare module 'react-tools/src/test/createHierarchyRenderer.js' {
  declare module.exports: $Exports<'react-tools/src/test/createHierarchyRenderer'>;
}
declare module 'react-tools/src/test/getTestDocument.js' {
  declare module.exports: $Exports<'react-tools/src/test/getTestDocument'>;
}
declare module 'react-tools/src/test/MetaMatchers.js' {
  declare module.exports: $Exports<'react-tools/src/test/MetaMatchers'>;
}
declare module 'react-tools/src/test/mock-modules.js' {
  declare module.exports: $Exports<'react-tools/src/test/mock-modules'>;
}
declare module 'react-tools/src/test/mock-timers.js' {
  declare module.exports: $Exports<'react-tools/src/test/mock-timers'>;
}
declare module 'react-tools/src/test/mocks.js' {
  declare module.exports: $Exports<'react-tools/src/test/mocks'>;
}
declare module 'react-tools/src/test/phantomjs-shims.js' {
  declare module.exports: $Exports<'react-tools/src/test/phantomjs-shims'>;
}
declare module 'react-tools/src/test/reactComponentExpect.js' {
  declare module.exports: $Exports<'react-tools/src/test/reactComponentExpect'>;
}
declare module 'react-tools/src/test/ReactDefaultPerf.js' {
  declare module.exports: $Exports<'react-tools/src/test/ReactDefaultPerf'>;
}
declare module 'react-tools/src/test/ReactDefaultPerfAnalysis.js' {
  declare module.exports: $Exports<'react-tools/src/test/ReactDefaultPerfAnalysis'>;
}
declare module 'react-tools/src/test/ReactPerf.js' {
  declare module.exports: $Exports<'react-tools/src/test/ReactPerf'>;
}
declare module 'react-tools/src/test/ReactTestUtils.js' {
  declare module.exports: $Exports<'react-tools/src/test/ReactTestUtils'>;
}
declare module 'react-tools/src/test/worker.js' {
  declare module.exports: $Exports<'react-tools/src/test/worker'>;
}
declare module 'react-tools/src/utils/__tests__/accumulateInto-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/accumulateInto-test'>;
}
declare module 'react-tools/src/utils/__tests__/cloneWithProps-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/cloneWithProps-test'>;
}
declare module 'react-tools/src/utils/__tests__/escapeTextContentForBrowser-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/escapeTextContentForBrowser-test'>;
}
declare module 'react-tools/src/utils/__tests__/joinClasses-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/joinClasses-test'>;
}
declare module 'react-tools/src/utils/__tests__/memoizeStringOnly-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/memoizeStringOnly-test'>;
}
declare module 'react-tools/src/utils/__tests__/onlyChild-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/onlyChild-test'>;
}
declare module 'react-tools/src/utils/__tests__/OrderedMap-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/OrderedMap-test'>;
}
declare module 'react-tools/src/utils/__tests__/PooledClass-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/PooledClass-test'>;
}
declare module 'react-tools/src/utils/__tests__/quoteAttributeValueForBrowser-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/quoteAttributeValueForBrowser-test'>;
}
declare module 'react-tools/src/utils/__tests__/ReactChildren-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/ReactChildren-test'>;
}
declare module 'react-tools/src/utils/__tests__/sliceChildren-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/sliceChildren-test'>;
}
declare module 'react-tools/src/utils/__tests__/Transaction-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/Transaction-test'>;
}
declare module 'react-tools/src/utils/__tests__/traverseAllChildren-test.js' {
  declare module.exports: $Exports<'react-tools/src/utils/__tests__/traverseAllChildren-test'>;
}
declare module 'react-tools/src/utils/accumulate.js' {
  declare module.exports: $Exports<'react-tools/src/utils/accumulate'>;
}
declare module 'react-tools/src/utils/accumulateInto.js' {
  declare module.exports: $Exports<'react-tools/src/utils/accumulateInto'>;
}
declare module 'react-tools/src/utils/adler32.js' {
  declare module.exports: $Exports<'react-tools/src/utils/adler32'>;
}
declare module 'react-tools/src/utils/CallbackQueue.js' {
  declare module.exports: $Exports<'react-tools/src/utils/CallbackQueue'>;
}
declare module 'react-tools/src/utils/cloneWithProps.js' {
  declare module.exports: $Exports<'react-tools/src/utils/cloneWithProps'>;
}
declare module 'react-tools/src/utils/deprecated.js' {
  declare module.exports: $Exports<'react-tools/src/utils/deprecated'>;
}
declare module 'react-tools/src/utils/escapeTextContentForBrowser.js' {
  declare module.exports: $Exports<'react-tools/src/utils/escapeTextContentForBrowser'>;
}
declare module 'react-tools/src/utils/flattenChildren.js' {
  declare module.exports: $Exports<'react-tools/src/utils/flattenChildren'>;
}
declare module 'react-tools/src/utils/forEachAccumulated.js' {
  declare module.exports: $Exports<'react-tools/src/utils/forEachAccumulated'>;
}
declare module 'react-tools/src/utils/getIteratorFn.js' {
  declare module.exports: $Exports<'react-tools/src/utils/getIteratorFn'>;
}
declare module 'react-tools/src/utils/isTextInputElement.js' {
  declare module.exports: $Exports<'react-tools/src/utils/isTextInputElement'>;
}
declare module 'react-tools/src/utils/joinClasses.js' {
  declare module.exports: $Exports<'react-tools/src/utils/joinClasses'>;
}
declare module 'react-tools/src/utils/memoizeStringOnly.js' {
  declare module.exports: $Exports<'react-tools/src/utils/memoizeStringOnly'>;
}
declare module 'react-tools/src/utils/onlyChild.js' {
  declare module.exports: $Exports<'react-tools/src/utils/onlyChild'>;
}
declare module 'react-tools/src/utils/OrderedMap.js' {
  declare module.exports: $Exports<'react-tools/src/utils/OrderedMap'>;
}
declare module 'react-tools/src/utils/PooledClass.js' {
  declare module.exports: $Exports<'react-tools/src/utils/PooledClass'>;
}
declare module 'react-tools/src/utils/quoteAttributeValueForBrowser.js' {
  declare module.exports: $Exports<'react-tools/src/utils/quoteAttributeValueForBrowser'>;
}
declare module 'react-tools/src/utils/ReactChildren.js' {
  declare module.exports: $Exports<'react-tools/src/utils/ReactChildren'>;
}
declare module 'react-tools/src/utils/shallowEqual.js' {
  declare module.exports: $Exports<'react-tools/src/utils/shallowEqual'>;
}
declare module 'react-tools/src/utils/sliceChildren.js' {
  declare module.exports: $Exports<'react-tools/src/utils/sliceChildren'>;
}
declare module 'react-tools/src/utils/Transaction.js' {
  declare module.exports: $Exports<'react-tools/src/utils/Transaction'>;
}
declare module 'react-tools/src/utils/traverseAllChildren.js' {
  declare module.exports: $Exports<'react-tools/src/utils/traverseAllChildren'>;
}
declare module 'react-tools/src/vendor/core/camelize.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/camelize'>;
}
declare module 'react-tools/src/vendor/core/camelizeStyleName.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/camelizeStyleName'>;
}
declare module 'react-tools/src/vendor/core/createArrayFromMixed.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/createArrayFromMixed'>;
}
declare module 'react-tools/src/vendor/core/createNodesFromMarkup.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/createNodesFromMarkup'>;
}
declare module 'react-tools/src/vendor/core/CSSCore.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/CSSCore'>;
}
declare module 'react-tools/src/vendor/core/dom/containsNode.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/dom/containsNode'>;
}
declare module 'react-tools/src/vendor/core/dom/focusNode.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/dom/focusNode'>;
}
declare module 'react-tools/src/vendor/core/dom/getActiveElement.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/dom/getActiveElement'>;
}
declare module 'react-tools/src/vendor/core/dom/getUnboundedScrollPosition.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/dom/getUnboundedScrollPosition'>;
}
declare module 'react-tools/src/vendor/core/dom/isNode.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/dom/isNode'>;
}
declare module 'react-tools/src/vendor/core/dom/isTextNode.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/dom/isTextNode'>;
}
declare module 'react-tools/src/vendor/core/emptyFunction.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/emptyFunction'>;
}
declare module 'react-tools/src/vendor/core/emptyObject.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/emptyObject'>;
}
declare module 'react-tools/src/vendor/core/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/ExecutionEnvironment'>;
}
declare module 'react-tools/src/vendor/core/getMarkupWrap.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/getMarkupWrap'>;
}
declare module 'react-tools/src/vendor/core/hyphenate.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/hyphenate'>;
}
declare module 'react-tools/src/vendor/core/hyphenateStyleName.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/hyphenateStyleName'>;
}
declare module 'react-tools/src/vendor/core/invariant.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/invariant'>;
}
declare module 'react-tools/src/vendor/core/mapObject.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/mapObject'>;
}
declare module 'react-tools/src/vendor/core/monitorCodeUse.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/monitorCodeUse'>;
}
declare module 'react-tools/src/vendor/core/nativeRequestAnimationFrame.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/nativeRequestAnimationFrame'>;
}
declare module 'react-tools/src/vendor/core/requestAnimationFrame.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/requestAnimationFrame'>;
}
declare module 'react-tools/src/vendor/core/toArray.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/toArray'>;
}
declare module 'react-tools/src/vendor/core/TouchEventUtils.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/TouchEventUtils'>;
}
declare module 'react-tools/src/vendor/core/warning.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/core/warning'>;
}
declare module 'react-tools/src/vendor/key-mirror/__tests__/keyMirror-test.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/key-mirror/__tests__/keyMirror-test'>;
}
declare module 'react-tools/src/vendor/key-mirror/keyMirror.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/key-mirror/keyMirror'>;
}
declare module 'react-tools/src/vendor/key-mirror/keyOf.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/key-mirror/keyOf'>;
}
declare module 'react-tools/src/vendor/performance/performance.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/performance/performance'>;
}
declare module 'react-tools/src/vendor/performance/performanceNow.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/performance/performanceNow'>;
}
declare module 'react-tools/src/vendor/stubs/cx.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/stubs/cx'>;
}
declare module 'react-tools/src/vendor/stubs/EventListener.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/stubs/EventListener'>;
}
declare module 'react-tools/src/vendor/stubs/ReactErrorUtils.js' {
  declare module.exports: $Exports<'react-tools/src/vendor/stubs/ReactErrorUtils'>;
}
declare module 'react-tools/vendor/fbtransform/syntax.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/syntax'>;
}
declare module 'react-tools/vendor/fbtransform/transforms/__tests__/jsx-test.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/transforms/__tests__/jsx-test'>;
}
declare module 'react-tools/vendor/fbtransform/transforms/__tests__/react-displayName-test.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/transforms/__tests__/react-displayName-test'>;
}
declare module 'react-tools/vendor/fbtransform/transforms/__tests__/react-test.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/transforms/__tests__/react-test'>;
}
declare module 'react-tools/vendor/fbtransform/transforms/jsx.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/transforms/jsx'>;
}
declare module 'react-tools/vendor/fbtransform/transforms/react.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/transforms/react'>;
}
declare module 'react-tools/vendor/fbtransform/transforms/reactDisplayName.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/transforms/reactDisplayName'>;
}
declare module 'react-tools/vendor/fbtransform/visitors.js' {
  declare module.exports: $Exports<'react-tools/vendor/fbtransform/visitors'>;
}
declare module 'react-tools/vendor/inline-source-map.js' {
  declare module.exports: $Exports<'react-tools/vendor/inline-source-map'>;
}
