// flow-typed signature: c93c71db183241ada5a6015d29873daa
// flow-typed version: <<STUB>>/@emotion/react_v11.1.4/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/react/dist/emotion-element-3a01c80e.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-element-4fbd89c5.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-element-547f2a0a.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-element-9c6b0354.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-element-cb6e9ca7.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/dist/emotion-react.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.esm' {
  declare module.exports: any;
}

declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/react/macro' {
  declare module.exports: any;
}

declare module '@emotion/react/src/class-names' {
  declare module.exports: any;
}

declare module '@emotion/react/src/context' {
  declare module.exports: any;
}

declare module '@emotion/react/src/css' {
  declare module.exports: any;
}

declare module '@emotion/react/src/emotion-element' {
  declare module.exports: any;
}

declare module '@emotion/react/src/global' {
  declare module.exports: any;
}

declare module '@emotion/react/src' {
  declare module.exports: any;
}

declare module '@emotion/react/src/isolated-hoist-non-react-statics-do-not-use-this-in-your-code' {
  declare module.exports: any;
}

declare module '@emotion/react/src/jsx-dev-runtime' {
  declare module.exports: any;
}

declare module '@emotion/react/src/jsx-runtime' {
  declare module.exports: any;
}

declare module '@emotion/react/src/jsx' {
  declare module.exports: any;
}

declare module '@emotion/react/src/keyframes' {
  declare module.exports: any;
}

declare module '@emotion/react/src/theming' {
  declare module.exports: any;
}

declare module '@emotion/react/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/react/dist/emotion-element-3a01c80e.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-element-3a01c80e.cjs.prod'>;
}
declare module '@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-element-4fbd89c5.browser.esm'>;
}
declare module '@emotion/react/dist/emotion-element-547f2a0a.esm.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-element-547f2a0a.esm'>;
}
declare module '@emotion/react/dist/emotion-element-9c6b0354.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-element-9c6b0354.browser.cjs'>;
}
declare module '@emotion/react/dist/emotion-element-cb6e9ca7.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-element-cb6e9ca7.cjs.dev'>;
}
declare module '@emotion/react/dist/emotion-react.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.browser.cjs'>;
}
declare module '@emotion/react/dist/emotion-react.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.browser.esm'>;
}
declare module '@emotion/react/dist/emotion-react.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.cjs.dev'>;
}
declare module '@emotion/react/dist/emotion-react.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.cjs'>;
}
declare module '@emotion/react/dist/emotion-react.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.cjs.prod'>;
}
declare module '@emotion/react/dist/emotion-react.esm.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.esm'>;
}
declare module '@emotion/react/dist/emotion-react.umd.min.js' {
  declare module.exports: $Exports<'@emotion/react/dist/emotion-react.umd.min'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.browser.cjs'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.browser.esm'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.dev'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.cjs.prod'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.esm.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.esm'>;
}
declare module '@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.umd.min.js' {
  declare module.exports: $Exports<'@emotion/react/isolated-hoist-non-react-statics-do-not-use-this-in-your-code/dist/emotion-react-isolated-hoist-non-react-statics-do-not-use-this-in-your-code.umd.min'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.browser.cjs'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.browser.esm'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.dev'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.cjs.prod'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.esm'>;
}
declare module '@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.umd.min.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-dev-runtime/dist/emotion-react-jsx-dev-runtime.umd.min'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.browser.cjs'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.browser.esm'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.prod'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.esm.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.esm'>;
}
declare module '@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.umd.min.js' {
  declare module.exports: $Exports<'@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.umd.min'>;
}
declare module '@emotion/react/macro.js' {
  declare module.exports: $Exports<'@emotion/react/macro'>;
}
declare module '@emotion/react/src/class-names.js' {
  declare module.exports: $Exports<'@emotion/react/src/class-names'>;
}
declare module '@emotion/react/src/context.js' {
  declare module.exports: $Exports<'@emotion/react/src/context'>;
}
declare module '@emotion/react/src/css.js' {
  declare module.exports: $Exports<'@emotion/react/src/css'>;
}
declare module '@emotion/react/src/emotion-element.js' {
  declare module.exports: $Exports<'@emotion/react/src/emotion-element'>;
}
declare module '@emotion/react/src/global.js' {
  declare module.exports: $Exports<'@emotion/react/src/global'>;
}
declare module '@emotion/react/src/index' {
  declare module.exports: $Exports<'@emotion/react/src'>;
}
declare module '@emotion/react/src/index.js' {
  declare module.exports: $Exports<'@emotion/react/src'>;
}
declare module '@emotion/react/src/isolated-hoist-non-react-statics-do-not-use-this-in-your-code.js' {
  declare module.exports: $Exports<'@emotion/react/src/isolated-hoist-non-react-statics-do-not-use-this-in-your-code'>;
}
declare module '@emotion/react/src/jsx-dev-runtime.js' {
  declare module.exports: $Exports<'@emotion/react/src/jsx-dev-runtime'>;
}
declare module '@emotion/react/src/jsx-runtime.js' {
  declare module.exports: $Exports<'@emotion/react/src/jsx-runtime'>;
}
declare module '@emotion/react/src/jsx.js' {
  declare module.exports: $Exports<'@emotion/react/src/jsx'>;
}
declare module '@emotion/react/src/keyframes.js' {
  declare module.exports: $Exports<'@emotion/react/src/keyframes'>;
}
declare module '@emotion/react/src/theming.js' {
  declare module.exports: $Exports<'@emotion/react/src/theming'>;
}
declare module '@emotion/react/src/utils.js' {
  declare module.exports: $Exports<'@emotion/react/src/utils'>;
}
