// flow-typed signature: 118c5c1f17ada80d5e6be712aeba4dac
// flow-typed version: <<STUB>>/@emotion/styled_v11.0.0/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/styled/base/dist/emotion-styled-base.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled/base/dist/emotion-styled-base.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled/base/dist/emotion-styled-base.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/styled/base/dist/emotion-styled-base.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled/base/dist/emotion-styled-base.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/styled/base/dist/emotion-styled-base.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled/base/dist/emotion-styled-base.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.browser.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.browser.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.cjs' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.esm' {
  declare module.exports: any;
}

declare module '@emotion/styled/dist/emotion-styled.umd.min' {
  declare module.exports: any;
}

declare module '@emotion/styled/macro' {
  declare module.exports: any;
}

declare module '@emotion/styled/src/base' {
  declare module.exports: any;
}

declare module '@emotion/styled/src' {
  declare module.exports: any;
}

declare module '@emotion/styled/src/tags' {
  declare module.exports: any;
}

declare module '@emotion/styled/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/styled/base/dist/emotion-styled-base.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.browser.cjs'>;
}
declare module '@emotion/styled/base/dist/emotion-styled-base.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.browser.esm'>;
}
declare module '@emotion/styled/base/dist/emotion-styled-base.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.cjs.dev'>;
}
declare module '@emotion/styled/base/dist/emotion-styled-base.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.cjs'>;
}
declare module '@emotion/styled/base/dist/emotion-styled-base.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.cjs.prod'>;
}
declare module '@emotion/styled/base/dist/emotion-styled-base.esm.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.esm'>;
}
declare module '@emotion/styled/base/dist/emotion-styled-base.umd.min.js' {
  declare module.exports: $Exports<'@emotion/styled/base/dist/emotion-styled-base.umd.min'>;
}
declare module '@emotion/styled/dist/emotion-styled.browser.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.browser.cjs'>;
}
declare module '@emotion/styled/dist/emotion-styled.browser.esm.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.browser.esm'>;
}
declare module '@emotion/styled/dist/emotion-styled.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.cjs.dev'>;
}
declare module '@emotion/styled/dist/emotion-styled.cjs.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.cjs'>;
}
declare module '@emotion/styled/dist/emotion-styled.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.cjs.prod'>;
}
declare module '@emotion/styled/dist/emotion-styled.esm.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.esm'>;
}
declare module '@emotion/styled/dist/emotion-styled.umd.min.js' {
  declare module.exports: $Exports<'@emotion/styled/dist/emotion-styled.umd.min'>;
}
declare module '@emotion/styled/macro.js' {
  declare module.exports: $Exports<'@emotion/styled/macro'>;
}
declare module '@emotion/styled/src/base.js' {
  declare module.exports: $Exports<'@emotion/styled/src/base'>;
}
declare module '@emotion/styled/src/index' {
  declare module.exports: $Exports<'@emotion/styled/src'>;
}
declare module '@emotion/styled/src/index.js' {
  declare module.exports: $Exports<'@emotion/styled/src'>;
}
declare module '@emotion/styled/src/tags.js' {
  declare module.exports: $Exports<'@emotion/styled/src/tags'>;
}
declare module '@emotion/styled/src/utils.js' {
  declare module.exports: $Exports<'@emotion/styled/src/utils'>;
}
