// flow-typed signature: 5c997c92db3a1012eee2359b129d0d34
// flow-typed version: <<STUB>>/redux-saga-tester_v1.0.874/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-tester'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-tester' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-tester/dist/SagaTester' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/examples/example.debounce' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/examples/example.multiple.waitfor' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/examples/example.nock' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/src/SagaTester' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/test/SagaTester.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-tester/dist/SagaTester.js' {
  declare module.exports: $Exports<'redux-saga-tester/dist/SagaTester'>;
}
declare module 'redux-saga-tester/examples/example.debounce.js' {
  declare module.exports: $Exports<'redux-saga-tester/examples/example.debounce'>;
}
declare module 'redux-saga-tester/examples/example.multiple.waitfor.js' {
  declare module.exports: $Exports<'redux-saga-tester/examples/example.multiple.waitfor'>;
}
declare module 'redux-saga-tester/examples/example.nock.js' {
  declare module.exports: $Exports<'redux-saga-tester/examples/example.nock'>;
}
declare module 'redux-saga-tester/src/SagaTester.js' {
  declare module.exports: $Exports<'redux-saga-tester/src/SagaTester'>;
}
declare module 'redux-saga-tester/test/SagaTester.spec.js' {
  declare module.exports: $Exports<'redux-saga-tester/test/SagaTester.spec'>;
}
